name: DifferentiableEvaporation
channels:
  - conda-forge
  - defaults 
dependencies:
  - python=3.12
  - xee=0.0.19
  - matplotlib
  - hvplot 
  - geoviews
  - jupyterlab 
  - netcdf4
  - owslib
  - rioxarray
  - soilgrids=0.1.4 
  - cubo=2024.8.0
  - pip
  - pip:
    - zenodo_get
    - icoscp==0.2.2
    - timezonefinder