name: DifferentiableEvaporation
channels:
  - conda-forge
  - defaults 
dependencies:
  - python=3.12
  - xee=0.0.19
  - matplotlib=3.10.*
  - hvplot=0.11.*
  - geoviews=1.14.*
  - jupyterlab=4.3.*
  - netcdf4=1.7.*
  - owslib=0.32.*
  - rioxarray=0.18.*
  - soilgrids=0.1.4 
  - cubo=2024.8.0
  - pip
  - pip:
    - zenodo_get==1.6.*
    - icoscp==0.2.2
    - timezonefinder==6.5.*