name: DifferentiableEvaporation
channels:
  - conda-forge
  - defaults 
dependencies:
  - python=3.12
  - xee
  - matplotlib
  - hvplot 
  - geoviews
  - jupyterlab 
  - netcdf4
  - owslib
  - rioxarray
  - soilgrids 
  - cubo
  - gdal
  - pip
  - pip:
    - zenodo_get