name = "EvaporationModel"
uuid = "49da8130-70c8-449e-9091-2395ad2fb07e"
authors = ["Olivier Bonte <olivier.bonte@hotmail.com>"]
version = "0.1.0"

[deps]
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
